/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package team10;

/**
 *
 * @author sabri
 */
public class Ajout_Evenement extends javax.swing.JFrame {

    /**
     * Creates new form Ajout_Evenement
     */
    public Ajout_Evenement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        Déconnexion = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel1.setForeground(java.awt.Color.black);
        jLabel1.setText("Nom De l'événement");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 30, 150, 20);

        jLabel2.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel2.setForeground(java.awt.Color.black);
        jLabel2.setText("Nom Du Créateur");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 80, 130, 20);

        jLabel3.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel3.setForeground(java.awt.Color.black);
        jLabel3.setText("Salle");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 130, 60, 20);

        jLabel4.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel4.setForeground(java.awt.Color.black);
        jLabel4.setText("Heure de Début");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 170, 109, 20);

        jLabel5.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel5.setForeground(java.awt.Color.black);
        jLabel5.setText("Heure de Fin");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 210, 100, 20);

        jLabel6.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel6.setForeground(java.awt.Color.black);
        jLabel6.setText("Classe");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 250, 60, 20);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(210, 30, 112, 30);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(210, 80, 112, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Amphi", "A0.1", "A0.2", "A2.1", "A2.2", "B0.1", "B0.2", "B0.3", "B1.1", "B1.2", "B1.3", "B2.1", "B2.2", "R0.1", "R0.2", "R0.3", "R0.4", "R2.1", "Labo Info 0.1", "Labo Info 0.2", "Labo Info 0.3", "Labo Info 1.1", "Labo Info 1.2", "Labo Info 2.1", "Labo Info 2.2", "Labo Mec 0.1", "Labo Mec 0.2", "Hall Mec", "Labo Elec 0.1", "Labo Elec 0.2", "Labo Elec 1.1", "Labo Elec 1.2" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(210, 120, 112, 30);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IA2.1", "IA2.2", "IA2.3" }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(210, 250, 112, 30);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10:00", "11:40", "13:20", "15:00", "16:40", "18:20" }));
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(210, 210, 112, 30);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "08:30", "10:10", "11:50", "13:30", "15:10", "16:50", " " }));
        getContentPane().add(jComboBox4);
        jComboBox4.setBounds(210, 170, 112, 30);

        Déconnexion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team10/images/logout.png"))); // NOI18N
        Déconnexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DéconnexionActionPerformed(evt);
            }
        });
        getContentPane().add(Déconnexion);
        Déconnexion.setBounds(350, 270, 40, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team10/images/arriere.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(-110, -40, 680, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DéconnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DéconnexionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DéconnexionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ajout_Evenement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ajout_Evenement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ajout_Evenement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ajout_Evenement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ajout_Evenement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Déconnexion;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
